name: Bug Report
description: Report a reproducible bug in Mizban
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please fill out enough detail so we can reproduce quickly.
  - type: input
    id: version
    attributes:
      label: Mizban Version
      description: "Example: 3.0.0"
      placeholder: 3.0.0
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      description: OS + architecture
      placeholder: Windows 11 amd64 / Ubuntu 24.04 amd64 / macOS arm64
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Start mizban
        2. Open URL ...
        3. Upload file ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant terminal output, stack traces, or screenshots.
